# File: apps.py
# Description: Autogenerated file from the "django-admin startapp" facility
# Author: Chris Knowles
# Date: Jun 2023


from django.apps import AppConfig


class AppointmentsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'appointments'
