# File: views.py
# Description: Autogenerated file from the "django-admin startapp" facility - modified for the specific
#              application "panda/appointments"
# Author: Chris Knowles
# Date: Jun 2023


from django.http import HttpRequest, HttpResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def create_patient(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


@csrf_exempt
def retrieve_patient(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


@csrf_exempt
def update_patient(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


def delete_patient(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


@csrf_exempt
def create_appointment(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


def retrieve_appointments(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


@csrf_exempt
def update_appointment(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)


def delete_appointment(response: HttpRequest) -> HttpResponse:
    response = 0
    return HttpResponse(response)
