# File: asgi.py
# Description: Autogenerated file from the "django-admin startproject" facility
# Author: Chris Knowles
# Date: Jun 2023


"""
ASGI config for panda project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'panda.settings')

application = get_asgi_application()
