# File: wsgi.py
# Description: Autogenerated file from the "django-admin startproject" facility
# Author: Chris Knowles
# Date: Jun 2023


"""
WSGI config for panda project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'panda.settings')

application = get_wsgi_application()
